IBM LLM initiated
decisionfacts/semantic-ai pull request #11
Opened 2023-11-17 08:06 UTC by Balamurugan35

2023-11-17 09:36 UTC, SyedHabibM requested changes

2023-11-17 09:36 UTC, SyedHabibM commented on setup.py
version should be changed/updated?!

2023-11-17 10:16 UTC, Balamurugan35 commented on setup.py
New package added

2023-11-17 12:38 UTC, SyedHabibM requested changes

2023-11-17 12:38 UTC, SyedHabibM commented on semantic_ai/llm/ibm.py
> +            project_id=ibm_llm_project_id,
We can directly use `self.project_id` here.

2023-11-29 07:56 UTC, SyedHabibM approved these changes

2023-11-29 07:57 UTC, SyedHabibM commented
@PrabhuRaghav Plz verify and approve.

2023-11-29 12:35 UTC, PrabhuRaghav approved these changes

2023-11-29 12:36 UTC, PrabhuRaghav commented
> @PrabhuRaghav Plz verify and approve.

@SyedHabibM PRs reviewed and approved

2023-11-29 12:40 UTC, merged